name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: repo-490410
  REGION: europe-west1
  REPOSITORY: java-spting-boot
  SERVICE: spring-demo
  IMAGE: europe-west1-docker.pkg.dev/repo-490410/my-repo/spring-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SA }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push image
        run: |
          docker build -t ${{ env.IMAGE }}:${{ github.sha }} .
          docker push ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.IMAGE }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 8080 \
            --memory 512Mi \
            --add-cloudsql-instances repo-490410:europe-west1:spring-db \
            --set-env-vars DB_URL="jdbc:postgresql:///springdb?cloudSqlInstance=repo-490410:europe-west1:spring-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory",DB_USER="${{ secrets.DB_USER }}",DB_PASS="${{ secrets.DB_PASS }}"